# Generated by Django 5.0.4 on 2024-04-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_remove_students_course_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionYearModel',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
