# Generated by Django 5.0.4 on 2024-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_delete_sessionyearmodel_delete_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default='2000-04-25'),
            preserve_default=False,
        ),
    ]
